"""Generate FIST.MAC = a MACRO-11 transcription of the sprite decoder, run
against the captured test vector and verified byte-exact against FEXP via
the VRAM oracle.

Ports the captured fighter's path ($C40E=04, $C407=0): $8833 prologue + bit2
staging (RRD) + the $8A30 masked-shift blit, composing into the flat 13-wide
buffer FBUF.  Z80 work addresses $8AE0..$8B1F map to a 64-byte work area W
(offset = addr-$8AE0); tables, control stream, initial background (FINIT) and
expected buffer (FEXP) come from fighter_data.

Built incrementally and oracle-verified.  STAGE_LEVEL selects how much of the
decoder is emitted so each piece can be validated:
  0 = no decode (FBUF stays = FINIT; verifies the data/build/oracle pipeline)
  (higher levels add the real decoder as it is ported)

The harness copies FBUF into VRAM[0..884] so the oracle's VRAM dump can be
compared to FINIT (level 0) or FEXP (full).
"""
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import fighter_data as fd                                    # noqa: E402
from decoder_ref import run_loop                             # noqa: E402

OUT_MAC = HERE.parent / "FIST.MAC"
FEXP_BIN = HERE.parent / "fght_expected.bin"
FINIT_BIN = HERE.parent / "fght_initial.bin"

STAGE_LEVEL = int(os.environ.get("FGHT_LEVEL", "0"))


def _bytes_block(label, data, per=16):
    out = [f"{label}:"]
    for i in range(0, len(data), per):
        out.append("        .BYTE   " + ",".join(f"{b}." for b in data[i:i + per]))
    return "\n".join(out) + "\n"


HEADER = r"""        .TITLE  FIST
;
; The Way Of The Exploding Fist - MS-0515 port.
; MACRO-11 transcription of the procedural sprite decoder, generated by
; source/fighter_mac.py and verified byte-exact against the reference.
;
DPRAM  = 157700
DISPAT = 177400
SYSC   = 177604
VRAM   = 40000


        .EVEN
START:  MOV     #340,R0
        MTPS    R0
        MOV     @#DISPAT,ORIGDP
        MOVB    @#SYSC,ORIGRC
        MOVB    @#SYSC,R0
        BIC     #17,R0
        MOVB    R0,@#SYSC
        MOV     #3377,@#DPRAM
        MOV     #3377,@#DISPAT

        JSR     PC,SETUP               ; FBUF := FINIT (background)
        JSR     PC,DECRUN              ; run the decoder (no-op at level 0)
        JSR     PC,TOVRAM              ; FBUF -> VRAM[0..884] for the oracle

WKEY:   MOV     @#177442,R0
        BIT     #2,R0
        BEQ     WKEY
        MOV     ORIGDP,@#DPRAM
        MOV     ORIGDP,@#DISPAT
        MOVB    ORIGRC,@#SYSC
        EMT     350


;-------------------------------------------------------------------
SETUP:  MOV     #WINIT,R0              ; load work area ($8AE0.. flags)
        MOV     #W,R1
        MOV     #64.,R2
1$:     MOVB    (R0)+,(R1)+
        DEC     R2
        BNE     1$
        MOV     #FINIT,R0              ; FBUF := background
        MOV     #FBUF,R1
        MOV     #884.,R2
2$:     MOVB    (R0)+,(R1)+
        DEC     R2
        BNE     2$
        RTS     PC

TOVRAM: MOV     #FBUF,R0
        MOV     #VRAM,R1
        MOV     #884.,R2
1$:     MOVB    (R0)+,(R1)+
        DEC     R2
        BNE     1$
        RTS     PC

"""

# Level 0: decoder is a no-op (FBUF stays = FINIT).
DECRUN_L0 = """;-------------------------------------------------------------------
DECRUN: RTS     PC                      ; level 0: no decode
"""

# Level 1: full decoder for the captured path ($C40E=04 bit2, $C407=0).
# Transcribed from decoder_ref.py.  R4=HL (source), R3=DE (dest in FBUF),
# R0/R1/R2/R5 scratch.  Work addrs $8AE0.. -> W+(addr-$8AE0); C408V = stride.
DECRUN_L1 = r"""C408V  = %C408%.

;-------------------------------------------------------------------
; DECRUN - run the $8833 -> $8A30 element loop over the control stream.
DECRUN: MOV     #FCTRL,SRCP
        MOV     #FBUF+%DEOFF%.,DSTP
        MOV     #%NELEM%.,NCOUNT
DLOOP:  JSR     PC,STAGE               ; R0 = $8B01 ptr, or 0 at terminator
        TST     R0
        BEQ     1$
        MOV     R0,R4                  ; HL = $8B01 (work stream)
        MOV     DSTP,R3                ; DE = current dest
        JSR     PC,DECODE
        MOV     WHL14,SRCP             ; reload next src/dest ($8B14/$8B16)
        MOV     WDE16,DSTP
        DEC     NCOUNT
        BNE     DLOOP
1$:     RTS     PC

;-------------------------------------------------------------------
; STAGE - $8833 prologue + bit2 staging.  In: SRCP=HL, DSTP=DE.
; Out: R0 = &$8B01 work stream, or 0 at terminator.
STAGE:  MOVB    WAF3,R0                 ; toggle $8AF3 bit0
        COM     R0
        BIC     #177776,R0
        MOVB    R0,WAF3
        CLRB    WAFE
        CLRB    WAFF
        MOV     SRCP,R4
        MOVB    (R4),R0
        BIC     #177400,R0
        BNE     1$
        CLR     R0                     ; terminator
        RTS     PC
1$:     MOV     DSTP,R3
        MOV     R3,R0                  ; $8B16 = DE + C408
        ADD     #C408V,R0
        MOV     R0,WDE16
        MOVB    (R4),R0
        BIC     #177400,R0
        BIT     #200,R0                ; ctrl bit7
        BEQ     2$
        MOV     R0,R1                  ; bit7: $8B14 = HL + (ctrl&7)+1
        BIC     #177770,R1
        INC     R1
        MOV     R4,R2
        ADD     R1,R2
        MOV     R2,WHL14
        BR      3$
2$:     MOVB    WB1B,R1                ; clear: $8B14 = HL + B1B, stage into $8AE9
        BIC     #177400,R1
        MOV     R4,R2
        ADD     R1,R2
        MOV     R2,WHL14
        MOVB    WB1B,R0
        BIS     #200,R0
        MOVB    R0,WAE9
        MOV     #WAE9,R2
        INC     R2
        MOV     R4,R0
        MOVB    WB1B,R1
        BIC     #177400,R1
        BEQ     22$
21$:    MOVB    (R0)+,(R2)+
        DEC     R1
        BNE     21$
22$:    MOV     #WAE9,R4
3$:     TSTB    C407M                  ; $8882 facing mirror?
        BEQ     30$
        JSR     PC,FACING              ; R4 = $8AF4
30$:    BITB    #1,C40EM               ; mode dispatch ($88A5/$88F7/$8965/$89C2)
        BEQ     31$
        JSR     PC,MBIT0               ; bit0: $B700 mirror-x prefix, R4 = $8B0B
31$:    BITB    #2,C40EM
        BEQ     32$
        JMP     MBIT1                  ; bit1 (RRA); returns $8B01 to DLOOP
32$:    BITB    #4,C40EM
        BEQ     33$
        JMP     MBIT2                  ; bit2 (RRD)
33$:    BITB    #10,C40EM
        BEQ     34$
        JMP     MBIT3                  ; bit3 (RLA)
34$:    MOV     R4,R0                  ; no mode bits: return HL
        RTS     PC

;-------------------------------------------------------------------
; MBIT2 - bit2 element staging (RRD scaling, thresh $10).  In: R4=HL.
MBIT2:  MOVB    (R4)+,R0
        BIC     #177400,R0
        MOVB    R0,W8B01
        BIC     #177770,R0
        BNE     4$
        MOV     #W8B01,R0
        RTS     PC
4$:     MOVB    R0,W8B00
        MOV     R0,R5
        MOVB    (R4),R0
        BIC     #177400,R0
        CMP     R0,#16.
        BGE     5$
        MOVB    #1,WAFE
5$:     MOV     #W8B02,R2
        MOV     R4,R0
        MOV     R5,R1
51$:    MOVB    (R0)+,(R2)+
        DEC     R1
        BNE     51$
        CLRB    (R2)
        INC     R5                     ; n = runlen+1; loop in R5 (DORRD clobbers R1/R3)
        MOV     #W8B02,R2
        CLR     R0
6$:     JSR     PC,DORRD
        INC     R2
        DEC     R5
        BNE     6$
        MOVB    -(R2),R0
        BIC     #177400,R0
        BNE     7$
        MOVB    #1,WAFF
7$:     MOV     #W8B01,R0
        RTS     PC

;-------------------------------------------------------------------
; MBIT1 - bit1 element staging (RRA x2 forward, thresh $04).  In: R4=HL.
MBIT1:  MOVB    (R4)+,R0
        BIC     #177400,R0
        MOVB    R0,W8B01
        BIC     #177770,R0
        BNE     1$
        MOV     #W8B01,R0
        RTS     PC
1$:     MOVB    R0,W8B00
        MOV     R0,R5
        MOVB    (R4),R0
        BIC     #177400,R0
        CMP     R0,#4.
        BGE     2$
        MOVB    #1,WAFE
2$:     MOV     #W8B02,R2
        MOV     R4,R0
        MOV     R5,R1
3$:     MOVB    (R0)+,(R2)+
        DEC     R1
        BNE     3$
        CLRB    (R2)
        MOVB    W8B00,R5               ; pass 1: RRA n bytes from $8B02
        INC     R5
        MOV     #W8B02,R2
        JSR     PC,RPASS
        MOVB    W8B00,R5               ; pass 2
        INC     R5
        MOV     #W8B02,R2
        JSR     PC,RPASS
        MOV     #W8B02,R2              ; last = $8B02 + runlen (= $8B02+n-1)
        MOVB    W8B00,R0
        ADD     R0,R2
        MOVB    (R2),R0
        BIC     #177400,R0
        BNE     4$
        MOVB    #1,WAFF
4$:     MOV     #W8B01,R0
        RTS     PC

;-------------------------------------------------------------------
; MBIT3 - bit3 element staging (RLA x2 backward, lead 0, thresh $40).
MBIT3:  MOVB    (R4)+,R0
        BIC     #177400,R0
        MOVB    R0,W8B01
        BIC     #177770,R0
        BNE     1$
        MOV     #W8B01,R0
        RTS     PC
1$:     MOVB    R0,W8B00
        MOV     R0,R5
        CLRB    W8B02                  ; leading 0 at $8B02; data at $8B03
        MOVB    (R4),R0
        BIC     #177400,R0
        CMP     R0,#40.
        BGE     2$
        MOVB    #1,WAFE
2$:     MOV     #W8B02+1,R2            ; copy runlen bytes -> $8B03
        MOV     R4,R0
        MOV     R5,R1
3$:     MOVB    (R0)+,(R2)+
        DEC     R1
        BNE     3$
        MOVB    W8B00,R0               ; p = $8B02 + runlen
        MOV     #W8B02,R2
        ADD     R0,R2                  ; R2 = p (LPASS start, backward)
        MOV     R2,-(SP)               ; save p
        MOVB    W8B00,R5               ; pass 1: RLA n bytes backward
        INC     R5
        JSR     PC,LPASS
        MOV     (SP),R2                ; restore p
        MOVB    W8B00,R5               ; pass 2
        INC     R5
        JSR     PC,LPASS
        MOV     (SP)+,R2               ; last = p
        MOVB    (R2),R0
        BIC     #177400,R0
        BNE     4$
        MOVB    #1,WAFF
4$:     MOV     #W8B01,R0
        RTS     PC

;-------------------------------------------------------------------
; MBIT0 - bit0 mirror-x prefix ($88AD) via $B700.  In: R4=HL; Out: R4=$8B0B.
MBIT0:  MOV     #W8B0B,R3              ; DE = $8B0B
        MOVB    (R4),R0                ; c = ctrl & 7
        BIC     #177774,R0
        MOV     R0,R5                  ; R5 = c
        MOVB    (R4),R0                ; b = (ctrl>>3) & 7
        BIC     #177400,R0
        ASR     R0
        ASR     R0
        ASR     R0
        BIC     #177770,R0             ; R0 = b
        MOVB    WB1B,R1                ; a = (B1B - b - c) << 3
        BIC     #177400,R1
        SUB     R0,R1
        SUB     R5,R1
        ASL     R1
        ASL     R1
        ASL     R1
        BIC     #177400,R1
        TST     R1
        BEQ     1$
        BIS     #100,R1                ; OR $40 if nonzero
1$:     BIS     #200,R1                ; OR $80
        MOVB    (R4),R0                ; (ctrl & 7) | hdr
        BIC     #177770,R0
        BIS     R1,R0
        MOVB    R0,(R3)+               ; store header byte
        MOVB    (R4)+,R0               ; c2 = ctrl & 7 ; hl++
        BIC     #177770,R0
        MOV     R0,R5                  ; R5 = c2
        ADD     R0,R3                  ; DE += c2
        DEC     R3                     ; DE--
        TST     R5
        BEQ     2$
3$:     MOVB    (R4)+,R0               ; m[de--] = $B700[m[hl++]]
        BIC     #177400,R0
        MOVB    TB700(R0),R1
        MOVB    R1,(R3)
        DEC     R3
        DEC     R5
        BNE     3$
2$:     MOV     #W8B0B,R4              ; HL = $8B0B
        RTS     PC

;-------------------------------------------------------------------
; FACING - $8882 facing mirror via $8AD1.  In: R4=HL; Out: R4=$8AF4.
FACING: MOV     #WAF4,R3
        MOVB    (R4)+,R0               ; first byte copied verbatim
        BIC     #177400,R0
        MOV     R0,R5                  ; count = first & 7
        BIC     #177770,R5
        MOVB    R0,(R3)+
        TST     R5
        BEQ     2$
1$:     MOVB    (R4)+,R0               ; m[de++] = transform(m[hl++])
        BIC     #177400,R0
        JSR     PC,XFORM
        MOVB    R0,(R3)+
        DEC     R5
        BNE     1$
2$:     MOV     #WAF4,R4
        RTS     PC

;-------------------------------------------------------------------
; XFORM - $8AD1: A = ($B800 if $8AF3 else $B900)[A].
XFORM:  TSTB    WAF3
        BEQ     1$
        MOVB    TB800(R0),R0
        BIC     #177400,R0
        RTS     PC
1$:     MOVB    TB900(R0),R0
        BIC     #177400,R0
        RTS     PC

;-------------------------------------------------------------------
; RPASS - RRA chain of R5 bytes forward from R2 (carry starts 0).
RPASS:  CLC
1$:     RORB    (R2)
        INC     R2
        DEC     R5
        BNE     1$
        RTS     PC

;-------------------------------------------------------------------
; LPASS - RLA chain of R5 bytes backward from R2 (carry starts 0).
LPASS:  CLC
1$:     ROLB    (R2)
        DEC     R2
        DEC     R5
        BNE     1$
        RTS     PC

;-------------------------------------------------------------------
; DORRD - Z80 RRD on (R2); A low byte in R0 (in/out).
DORRD:  MOVB    (R2),R1
        BIC     #177400,R1
        MOV     R0,R3
        BIC     #177760,R3             ; R3 = oldA & 0x0F (lo)
        BIC     #177417,R0             ; R0 = oldA & 0xF0
        MOV     R1,-(SP)
        BIC     #177760,R1             ; v & 0x0F
        BIS     R1,R0                  ; new A
        MOV     (SP)+,R1
        ASR     R1
        ASR     R1
        ASR     R1
        ASR     R1
        BIC     #177760,R1             ; (v>>4)&0x0F
        ASL     R3
        ASL     R3
        ASL     R3
        ASL     R3                     ; lo<<4
        BIS     R3,R1
        MOVB    R1,(R2)
        RTS     PC

;-------------------------------------------------------------------
; DECODE - $8A30 masked-shift blit.  In: R4=HL ($8B01), R3=DE (FBUF dest).
DECODE: MOVB    (R4),R0                ; a = m[hl]
        BIC     #177400,R0
        BIT     #100,R0                ; bit6 (carry after 2 RLA)?
        BEQ     8$
        MOVB    (R4),R1                ; x-skip = (a rotated left 6x through C, C=0) & 7
        BIC     #177400,R1
        CLC
        ROLB    R1
        ROLB    R1
        ROLB    R1
        ROLB    R1
        ROLB    R1
        ROLB    R1
        BIC     #177770,R1
        ADD     R1,R3                  ; DE += skip
8$:     MOVB    (R4),R0                ; count = m[hl] & 7
        BIC     #177400,R0
        BIC     #177770,R0
        BNE     9$
        RTS     PC                     ; count 0 -> $8AC6 (reload via loop)
9$:     MOV     R0,R2                  ; B = count
        MOVB    W8B0A,R1
        BIC     #177400,R1
        BEQ     10$
        INC     R2
10$:    INC     R4                     ; hl++ ; B--
        DEC     R2
        MOVB    WAFF,R1
        BIC     #177400,R1
        BEQ     11$
        DEC     R2
11$:    MOVB    WAFE,R1
        BIC     #177400,R1
        BEQ     12$
        INC     R3
        INC     R4
        DEC     R2
12$:    TST     R2
        BEQ     SINGLE
        ; leading byte: m[de] = (m[de] & TB500[src]) | src
        MOVB    (R4),R0
        BIC     #177400,R0
        MOVB    TB500(R0),R1
        BIC     #177400,R1
        COM     R1
        BIC     #177400,R1
        MOVB    (R3),R5
        BIC     #177400,R5
        BIC     R1,R5
        BIS     R0,R5
        MOVB    R5,(R3)
        INC     R3
        INC     R4
        DEC     R2
        TST     R2
        BEQ     TRAIL
13$:    MOVB    (R4)+,(R3)+            ; LDIR middle bytes
        DEC     R2
        BNE     13$
TRAIL:  MOVB    (R4),R0               ; trailing byte via TB600
        BIC     #177400,R0
        MOVB    TB600(R0),R1
        BIC     #177400,R1
        COM     R1
        BIC     #177400,R1
        MOVB    (R3),R5
        BIC     #177400,R5
        BIC     R1,R5
        BIS     R0,R5
        MOVB    R5,(R3)
        RTS     PC
SINGLE: MOVB    (R4),R0               ; $8AA5 single-byte case
        BIC     #177400,R0
        MOVB    TB500(R0),R2
        BIC     #177400,R2
        MOVB    TB600(R0),R1
        BIC     #177400,R1
        BIS     R2,R1                 ; l | c
        COM     R1
        BIC     #177400,R1
        MOVB    (R3),R5
        BIC     #177400,R5
        BIC     R1,R5
        BIS     R0,R5
        MOVB    R5,(R3)
        RTS     PC
"""

TAIL = r"""
;-------------------------------------------------------------------
ORIGDP: .WORD   0
ORIGRC: .WORD   0
SRCP:   .WORD   0
DSTP:   .WORD   0
NCOUNT: .WORD   0
C40EM:  .BYTE   %C40E%.                ; per-fighter mode flags ($C40E)
C407M:  .BYTE   %C407%.                ; facing flag ($C407)
        .EVEN
W:      .BLKB   64.
WAF3   = W+19.
WAF4   = W+20.
WAE9   = W+9.
WAFE   = W+30.
WAFF   = W+31.
W8B00  = W+32.
W8B01  = W+33.
W8B02  = W+34.
W8B0A  = W+42.
W8B0B  = W+43.
WHL14  = W+52.
WDE16  = W+54.
WB1B   = W+59.
"""


def emit_decrun():
    if STAGE_LEVEL == 0:
        return DECRUN_L0
    return DECRUN_L1


def main():
    nelem = int(os.environ.get("FGHT_NELEM", "5000"))
    c40e = int(os.environ.get("FGHT_C40E", "4"))
    c407 = int(os.environ.get("FGHT_C407", "0"))
    before, hl, de = fd.capture(c40e, c407)
    m = bytearray(before)
    run_loop(m, hl, de, limit=nelem)
    expected = bytes(m[fd.FBUF:fd.FBUF + fd.FBUF_LEN])
    initial = before[fd.FBUF:fd.FBUF + fd.FBUF_LEN]
    FEXP_BIN.write_bytes(expected)
    FINIT_BIN.write_bytes(initial)

    src = HEADER + emit_decrun() + TAIL + "\n"
    for t in fd.TABLES:
        src += _bytes_block(f"T{t:04X}", before[t:t + 256])
    src += _bytes_block("FCTRL", before[hl:hl + fd.STREAM_LEN])
    src += _bytes_block("FINIT", initial)
    src += _bytes_block("WINIT", before[0x8AE0:0x8B20])      # work-area flags
    src += "        .EVEN\nFBUF:   .BLKB   884.\n"
    src += "        .EVEN\n        .END    START\n"
    src = (src.replace("%C408%", str(before[0xC408]))
              .replace("%C40E%", str(before[0xC40E]))
              .replace("%C407%", str(before[0xC407]))
              .replace("%DEOFF%", str(de - fd.FBUF))
              .replace("%NELEM%", str(nelem)))
    src.encode("ascii")
    OUT_MAC.write_text(src, encoding="ascii", newline="\r\n")
    print(f"fighter_mac: wrote {OUT_MAC} (level {STAGE_LEVEL}, DE off {de - fd.FBUF})")


if __name__ == "__main__":
    main()
