"""Generate FIST.MAC = a MACRO-11 transcription of the sprite decoder, run
against the captured test vector and verified byte-exact against FEXP via
the VRAM oracle.

Ports the captured fighter's path ($C40E=04, $C407=0): $8833 prologue + bit2
staging (RRD) + the $8A30 masked-shift blit, composing into the flat 13-wide
buffer FBUF.  Z80 work addresses $8AE0..$8B1F map to a 64-byte work area W
(offset = addr-$8AE0); tables, control stream, initial background (FINIT) and
expected buffer (FEXP) come from fighter_data.

Built incrementally and oracle-verified.  STAGE_LEVEL selects how much of the
decoder is emitted so each piece can be validated:
  0 = no decode (FBUF stays = FINIT; verifies the data/build/oracle pipeline)
  (higher levels add the real decoder as it is ported)

The harness copies FBUF into VRAM[0..884] so the oracle's VRAM dump can be
compared to FINIT (level 0) or FEXP (full).
"""
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import fighter_data as fd                                    # noqa: E402
from decoder_ref import run_loop                             # noqa: E402

OUT_MAC = HERE.parent / "FIST.MAC"
FEXP_BIN = HERE.parent / "fght_expected.bin"
FINIT_BIN = HERE.parent / "fght_initial.bin"

STAGE_LEVEL = int(os.environ.get("FGHT_LEVEL", "0"))


def _bytes_block(label, data, per=16):
    out = [f"{label}:"]
    for i in range(0, len(data), per):
        out.append("        .BYTE   " + ",".join(f"{b}." for b in data[i:i + per]))
    return "\n".join(out) + "\n"


HEADER = r"""        .TITLE  FIST
;
; The Way Of The Exploding Fist - MS-0515 port.
; MACRO-11 transcription of the procedural sprite decoder, generated by
; source/fighter_mac.py and verified byte-exact against the reference.
;
DPRAM  = 157700
DISPAT = 177400
SYSC   = 177604
VRAM   = 40000


        .EVEN
START:  MOV     #340,R0
        MTPS    R0
        MOV     @#DISPAT,ORIGDP
        MOVB    @#SYSC,ORIGRC
        MOVB    @#SYSC,R0
        BIC     #17,R0
        MOVB    R0,@#SYSC
        MOV     #3377,@#DPRAM
        MOV     #3377,@#DISPAT

        JSR     PC,SETUP               ; FBUF := FINIT (background)
        JSR     PC,DECRUN              ; run the decoder (no-op at level 0)
        JSR     PC,TOVRAM              ; FBUF -> VRAM[0..884] for the oracle

WKEY:   MOV     @#177442,R0
        BIT     #2,R0
        BEQ     WKEY
        MOV     ORIGDP,@#DPRAM
        MOV     ORIGDP,@#DISPAT
        MOVB    ORIGRC,@#SYSC
        EMT     350


;-------------------------------------------------------------------
SETUP:  MOV     #FINIT,R0
        MOV     #FBUF,R1
        MOV     #884.,R2
1$:     MOVB    (R0)+,(R1)+
        DEC     R2
        BNE     1$
        RTS     PC

TOVRAM: MOV     #FBUF,R0
        MOV     #VRAM,R1
        MOV     #884.,R2
1$:     MOVB    (R0)+,(R1)+
        DEC     R2
        BNE     1$
        RTS     PC

"""

# Level 0: decoder is a no-op (FBUF stays = FINIT).
DECRUN_L0 = """;-------------------------------------------------------------------
DECRUN: RTS     PC                      ; level 0: no decode
"""

TAIL = r"""
;-------------------------------------------------------------------
ORIGDP: .WORD   0
ORIGRC: .WORD   0
"""


def emit_decrun():
    if STAGE_LEVEL == 0:
        return DECRUN_L0
    raise SystemExit(f"FGHT_LEVEL {STAGE_LEVEL} not yet implemented")


def main():
    before, hl, de = fd.capture()
    m = bytearray(before)
    run_loop(m, hl, de)
    expected = bytes(m[fd.FBUF:fd.FBUF + fd.FBUF_LEN])
    initial = before[fd.FBUF:fd.FBUF + fd.FBUF_LEN]
    FEXP_BIN.write_bytes(expected)
    FINIT_BIN.write_bytes(initial)

    src = HEADER + emit_decrun() + TAIL + "\n"
    for t in fd.TABLES:
        src += _bytes_block(f"T{t:04X}", before[t:t + 256])
    src += _bytes_block("FCTRL", before[hl:hl + fd.STREAM_LEN])
    src += _bytes_block("FINIT", initial)
    src += "        .EVEN\nFBUF:   .BLKB   884.\n"
    src += "        .EVEN\n        .END    START\n"
    src.encode("ascii")
    OUT_MAC.write_text(src, encoding="ascii", newline="\r\n")
    print(f"fighter_mac: wrote {OUT_MAC} (level {STAGE_LEVEL}, DE off {de - fd.FBUF})")


if __name__ == "__main__":
    main()
