"""gen_data.py - SAB2DT.MAC, the tune's data, from the original's tape.

The build's pre_build hook.  Reads the 48K tape in SAB2_DIR (see
sab2_dir.py) and writes next to the sources - build artifacts, never
committed, the tune is Rob Hubbard's and stays outside the repository:

  SAB2DT.MAC  TNDATA  the original's bytes 0xfe24..0xff8f as they sit in
                      the Spectrum's memory: the twelve periods of an
                      octave, the instruments, the patterns and the score,
                      the durations, the drum sequence and its patterns
                      (SAB2TN.MAC names the offsets)
              TNQTAB  the delay of a half period by its low byte L, in
                      sixteenths of a 30-clock turn: the original's loop
                      takes 16 T-states a half L and 32 more, and a T-state
                      is 15/7 clocks
              TNDRUM  five drums of twenty clicks: the spacing of each in
                      30-clock turns, from the twenty ROM bytes at 0x1000
                      the original reads, shifted right (drum - 1) times,
                      13 T-states a count, less what the engine's click
                      loop costs, the rounding carried from click to click
  SAB2TN.REF  the model's rendering of the tune as this machine plays it:
              every level change of the speaker with its T-state and its
              path tag - what the tests compare the engine's output with.
              The machine's frame is 150000 clocks = 70000 T-states, not
              the Spectrum's 69888, and the engine starts right after a
              frame tick (START_LAG_T later), so the interrupt falls in
              the same half period in both
"""
from pathlib import Path

from skoolkit import ROM48, read_bin_file

import engine_model
from tap48 import Memory, game_code

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
DATA_START = 0xfe24
DATA_END = 0xff90
NOISE_AT = 0x1000
CLICK_CLOCKS = 120          # the engine's click loop, less the wait
T_TO_CLOCKS = 15 / 7
MACHINE_FRAME_T = 70003     # 150007 clocks: the odd cycles of the instruction a frame ends in
START_LAG_T = 120           # the engine's entry after the tick it waits for


def qtab():
    return [round((16 * q + 32) * 16 / 14) for q in range(128)]


def drums(noise):
    """Five drums: twenty click spacings each, in whole turns, the error
    carried; the original's click is 65 + L T-states plus 13 a count,
    L = 16 for drum 1 (a NOP in its inner loop), 21 (drum - 1) - 5 after
    (RRA), and the last click's JR is 5 shorter."""
    out = []
    for drum in range(1, 6):
        shifts = drum - 1
        fixed = 65 + (16 if drum == 1 else 21 * shifts - 5)
        carry = 0.0
        row = []
        for i, byte in enumerate(noise):
            a = ((byte >> shifts) + 1) & 0xff
            if a == 0:
                a = 256
            t = fixed + 13 * a - (5 if i == 19 else 0)
            turns_exact = (t * T_TO_CLOCKS - CLICK_CLOCKS) / 30 + carry
            turns = max(0, round(turns_exact))
            carry = turns_exact - turns
            row.append(turns)
        out.append(row)
    return out


def words(name, values, per_line=8):
    lines = [f'{name}::']
    for i in range(0, len(values), per_line):
        chunk = ', '.join(f'{v & 0xffff:o}' for v in values[i:i + per_line])
        lines.append(f'        .WORD   {chunk}')
    return '\n'.join(lines)


def bytes_(name, data, per_line=12):
    lines = [f'{name}::']
    for i in range(0, len(data), per_line):
        chunk = ', '.join(f'{b:o}' for b in data[i:i + per_line])
        lines.append(f'        .BYTE   {chunk}')
    return '\n'.join(lines)


def main():
    code = game_code()
    mem = Memory(code)
    data = mem.region(DATA_START, DATA_END)
    rom = bytes(read_bin_file(ROM48))
    noise = rom[NOISE_AT:NOISE_AT + 20]

    text = '\n'.join([
        '        .TITLE  SAB2DT',
        '; SAB2DT.MAC - generated by source/gen_data.py from the original tape;',
        '; do not edit, do not commit (see the generator).',
        '        .GLOBL  TNDATA,TNQTAB,TNDRUM',
        '        .EVEN',
        bytes_('TNDATA', data),
        '        .EVEN',
        words('TNQTAB', qtab()),
        words('TNDRUM', [t for row in drums(noise) for t in row]),
        '        .END',
        '',
    ])
    (PROJECT / 'SAB2DT.MAC').write_text(text, newline='\r\n')

    engine = engine_model.Engine(code, rom, frame_t=MACHINE_FRAME_T,
                                 first_tick=MACHINE_FRAME_T - START_LAG_T)
    engine.run()
    with (PROJECT / 'SAB2TN.REF').open('w') as f:
        f.write(f'# frames {engine.frames}\n')
        for t, level, tag in engine.out:
            f.write(f'{t} {level} {tag}\n')
    print(f'SAB2DT.MAC: {len(data)} data bytes; SAB2TN.REF: {len(engine.out)} level changes, '
          f'{engine.frames} frames')


if __name__ == '__main__':
    main()
